### ISSUE TITLE
Player loadout

### ISSUE THREAD

**Issue by apazzolini** [pubgsh/client#21]
- [ ] Parse item equip/unequip events
- [ ] Determine UI/UX for rendering
- [ ] Implement rendering

**Comment by patrickgordon** [comment]
I'm keen to do this. Did you have an idea for UI/UX? I was thinking it could just be appended under the player name in the tooltip similar to how crate information works?

**Comment by patrickgordon** [comment]
I've started this. Beginning with parsing the equip and unequip events.

**Comment by apazzolini** [comment]
The equip/unequip event parsing is definitely the first step. You'll probably need to handle the two TODOs in `Telemetry.parser.js` since we'll definitely have nested structures (guns have can attachments for example).

My thoughts on the UI are:

1. Render a popup to the left of the roster (on top of the map) with details about a player when a player's name is hovered. This would include their loadout (possibly with the icons from https://github.com/pubg/api-assets), damage/kill stats, a link to their page (`pubg.sh/XXX/shard`), and probably checkboxes to toggle tracking them and their squad.

2. (Maybe) Once you're tracking a player (meaning you clicked on them and their name is underlined and visible on the map), render their loadout box on top of the roster. This would shift the roster down for every player you're tracking. I like the idea of this, but not sure how much space it will take up and if it's practical. Might need to clamp the max height of this element and then have two separate scrollbars, one for tracked loadouts and one for the remaining roster.

(BTW, If you'd like to talk through some of these things, you can find me on the PUBG developer Discord as BOT_Andre.)

**Comment by patrickgordon** [comment]
Cool I'll have a look at the telemetry parsing first. I also couldn't find the pubg developer discord so not sure if you can provide a link or something.

**Comment by apazzolini** [comment]
https://discord.gg/FcsT7t3

**Comment by apazzolini** [comment]
Resolved by #33
