### ISSUE TITLE
Ability to download telemetry and replay it locally

### ISSUE THREAD

**Issue by alvaro-cuesta** [pubgsh/client#39]
This is a feature request/idea.

As a pretty bad player it saddens me when I can no longer replay my few chicken dinners when they fall out of the recent matches.

Since telemetry is just a JSON file, the user could download it and retain the ability to play it locally via `<input type="file" />` and `FileReader` (no server interaction needed).

I have experience working on offline apps using `FileReader`, and I'm willing to work on this if you're interested in the idea.

**Comment by apazzolini** [comment]
Hey,

This is a bit more involved than you're suggesting. Right now, we need some server data to render even the match pages (duration, rosters, played at, game rank, etc). This is potentially all parseable from just the telemetry file (I don't know, needs investigation), but that's not the way the site is currently structured.

If you're interested in doing all of this, I'd be open to reviewing a pull request. I don't really play much PUBG any more though and can't justify working on this myself.

To get started, take a look at `routes/Match/index.js`. You'll need to make that `render()` work without the `this.props.data.match` attribute. You would have to trace down where that is passed in those components and refactor accordingly.

**Comment by alvaro-cuesta** [comment]
> This is a bit more involved than you're suggesting.

Of course, it's never as simple as it sounds :) I'm willing to spend some time on it if you think it's an useful feature.

I'm getting comfortable around the code and it seems feasible. I'm currently refactoring most `Match` code to separate presentation from fetching, so that two routes can share the `Match` component, but handle match+telemetry data either from Apollo+fetch or JSON.

There's only one thing I cannot grasp: why are you handling the case where a new `matchId` is updated in props? Is there any case where a route change is triggered from within the match route itself instead of mounting the component from scratch? I mean [here](https://github.com/pubgsh/client/blob/d60dbe8f2436439dd161b3399fec7aac9256418b/src/routes/Match/index.js#L122-L133).

Which leads me to: since I'm fetching telemetry data from the route component, `Match` always has `telemetry` so the autoplay feature (which detects [if telemetry was in `prevProps`](https://github.com/pubgsh/client/blob/d60dbe8f2436439dd161b3399fec7aac9256418b/src/routes/Match/Time/TimeTracker.js#L68-L88)) seems unnecessary now that my component is only mounted when I have telemetry.

Is is safe to remove those special cases? Seems like it is, but I'm not audacious enough to remove implicit knowledge that I might not fully grasp in a codebase I don't own.

Thanks for your time.

**Comment by apazzolini** [comment]
I think it's definitely a legitimate feature, and adding the UI for it is minimal enough that it won't clash with the site's design. I'm 100% on board with merging the feature.

I think the getDerivedStateFromProps usage is bad - incorrect usage of that lifecycle method, you're correct to remove it.

I agree with your comment on autoplay as well. We didn't want to start autoplay until telemetry was ready, but if you're adding a layer in between to delay the mounting of the component, that implicitly handles it.

Thanks for the great questions and working on this! Let me know if you have any other questions.

**Comment by alvaro-cuesta** [comment]
Glad to hear that.

I forgot to ask about [`options.tools.enabled`](https://github.com/pubgsh/client/blob/d60dbe8f2436439dd161b3399fec7aac9256418b/src/routes/Match/Time/TimeTracker.js#L72-L84). What is this?

**Comment by apazzolini** [comment]
That's correlated with [`Match/Options.js`](https://github.com/pubgsh/client/blob/d60dbe8f24/src/routes/Match/Options.js#L28-L41) - basically sometimes I wanted to have the hot refresh go to a specific zoom level / match progress to speed up development. Definitely want to keep that around.

And yes, the development build is slower (React adds dev-only checks, styled-components uses a different way of embedding CSS).

**Comment by alvaro-cuesta** [comment]
Resolved by #40 and #42
