### ISSUE TITLE
Plaeys icons and red zone only black

### ISSUE THREAD

**Issue by Zoltan1872** [pubgsh/client#50]
Hi,
I am using your software via PUBGlookup. On my android phone and older desktop it works fine, but on this brand new Windows 10PC, the map comes up in color, but all the player dots, name ID's on the map and red zone are solid black.

**Comment by apazzolini** [comment]
Hi,

I don't have time to fix this at the moment. I'll review a PR if you submit it. Otherwise, please try using Chrome or Firefox.

**Comment by Zoltan1872** [comment]
Yeah that worked using Chrome. Thanks.
