### ISSUE TITLE
pubg.sh is broken

### ISSUE THREAD

**Issue by briangleeson** [pubgsh/client#52]
@apazzolini love the site, but it appears to be broken right now. Don't know if you are aware?

Looks like V12 of the APIs went live on Thursday (20th June). Since then trying to load any game in pubg.sh results in "An error occured" when it is trying to load telemetry

V12 changes here: https://documentation.pubg.com/en/changelog/changelog.html#v12-0-0

**Comment by briangleeson** [comment]
Given that list of changes, this is the piece of code that is not working: https://github.com/pubgsh/client/blob/25e579aca29cdebc0e723643a728e841dcd71e13/src/models/Telemetry.parser.js#L188

Since LogPlayerKill.Killer can now be null, `d.killer.name` causes the error

**Comment by apazzolini** [comment]
Someone submitted this literally one minute before your bug report. https://github.com/pubgsh/client/pull/51

I'm going to merge it - should be deployed in about 5 minutes, let me know if it's still broken after that.

**Comment by briangleeson** [comment]
Ha, what timing! Hope this fixes it

**Comment by briangleeson** [comment]
@apazzolini its back! You can close this issue
