### ISSUE TITLE
Baltic_Main map (new Erangel) breaks replays

### ISSUE THREAD

**Issue by shawn42** [pubgsh/client#54]
It looks like a missing image (based on map name) is stopping it from loading. 
Example
https://pubg.sh/shawn42/steam/629e5a11-df03-4895-8984-f8da33b78e91

**Comment by Jubess** [comment]
Seems like something changed on PUBG's end with the new update. Baltic_Main refers to erangal 2.0 in the pubg code. I don't think it's a coincidence that pubg.sh doesn't show erangal anymore as map title.

**Comment by shawn42** [comment]
Exactly, my guess would be we need a new image named correctly and it may "just work".

**Comment by shawn42** [comment]
A quick grep of 'Erangel_Main' is probably enough to get started. For backwards compat it may be worth leaving Erangel_Main around, and just treating this like a new map.   ?

**Comment by apazzolini** [comment]
I pushed up a change to fix the crashing.

PUBG hasn't released an updated overview map asset yet, so it's using the old Erangel map for now. I'll update the map when it's available.

**Comment by Jubess** [comment]
Excellent job Andre!
