### ISSUE TITLE
Looks like maybe recent changes have broken the client

### ISSUE THREAD

**Issue by dalanmiller** [pubgsh/client#61]
```
  this.telemetryWorker.addEventListener('message', ({ data }) => {
            const { success, error, state, globalState, rawTelemetry } = data

            if (!success) {
                console.error(`Error loading telemetry: ${error}`)

                this.setState(prevState => ({
                    telemetryError: true,
                }))

                return
            }

            const telemetry = Telemetry(state)

            this.setState(prevState => ({
                rawTelemetry,
                telemetry,
                telemetryLoaded: true,
                rosters: telemetry.finalRoster(params.playerName),
                globalState,
            }))
        })
```

Getting: `Error loading telemetry: curState.players[_characterName] is undefined`

**Comment by apazzolini** [comment]
Hi, thanks for the report. I don't play PUBG anymore really, so unlikely for me to fix this anytime soon. Pull requests would be appreciated!

**Comment by dalanmiller** [comment]
Hey @apazzolini thanks for the encouragement! I took a crack this weekend but wasn't quite able to figure out what was going wrong as I'm pretty unfamiliar with GraphQL/Apollo, however I think I've narrowed it down to one or two of the following. I imagine with a few pointers I might be able to get it going: 

<img width="1135" alt="Screen Shot 2020-05-03 at 3 00 42 pm" src="https://user-images.githubusercontent.com/863286/80899080-2abe0e80-8cfb-11ea-8fe4-e59ec3dae300.png">

The first key thing seems to be that there are instances in the telemetry file where players are coming up without a name. Here's an example telemetry file: 

```
curl --compressed -v https://telemetry-cdn.playbattlegrounds.com/bluehole-pubg/console/2020/04/30/14/09/3c47ad8d-8aec-11ea-8105-ea77251b151c-telemetry.json
```

With many entries like this one:

```
{
    "character": {
      "name": "",
      "teamId": 0,
      "health": 0,
      "location": {
        "x": 334004.46875,
        "y": 477584.53125,
        "z": 9309.8310546875
      },
      "ranking": 0,
      "accountId": "",
      "isInBlueZone": true,
      "isInRedZone": true,
      "zone": []
    },
    "item": {
      "itemId": "Item_Back_F_01_Lv2_C",
      "stackCount": 1,
      "category": "Equipment",
      "subCategory": "Backpack",
      "attachedItems": []
    },
    "common": {
      "isGame": 1.5
    },
    "_D": "2020-04-30T13:47:11.854Z",
    "_T": "LogItemUnequip"
  },
```

The 2nd thing, may be the recent introduction of bots. For instance, if I connect to my running @pubgsh/server instance, and try pulling myself, it works. However, when I try to pull a bot such as `JGe_rSH3335` from the above mentioned telemetry, nothing is returned as it's not a real player. 

Two questions:

1. What is triggering [the localTelemetryWorker](https://github.com/pubgsh/client/blob/master/src/models/LocalTelemetry.worker.js) here? Is this a react thing? I wasn't able to see anywhere where anything was triggering the 'message' event. 
2. Does `Telemetry.parser.js` do some munging between the match data from the PUBG API and the telemetry data? 
3. I can get everything going in my Docker setup, however `yarn start` on my local machine doesn't actually kick off any server per your readme. As a sanity check, I ran `http-server` which appears to work fine and uses the same port.

**Comment by apazzolini** [comment]
Hey, thanks for doing this research, it was definitely helpful. I had a few other requests to fix this (including from a Patreon), so I dove in and fixed it. You can see what I did here if you're curious: https://github.com/pubgsh/client/commit/be100fb4447e2f08a87441f130829c9e5f6ebe7e 

It's not a perfect fix, but it stopped the crashing.
