### ISSUE TITLE
Bots blinks in the replays

### ISSUE THREAD

**Issue by Otsomies** [pubgsh/client#62]
Bots introduced in the PUBG patch 7.2 do not show properly in the replay. They blink in and out. 
This should be fixed. 

Also bots could be have some visual difference compared to real players. (Maybe different colour in the replay?)

**Comment by apazzolini** [comment]
It's something related to telemetry events not corresponding to a player that was retrieved from the backend roster. I'm not going to look into it further than that though.

**Comment by apazzolini** [comment]
Fixed.
