### ISSUE TITLE
Error loading telemetry

### ISSUE THREAD

**Issue by dalanmiller** [pubgsh/client#73]
```
Error loading telemetry: latestPlayerStates[playerName] is undefined index.js:63:24
```

Game with error:
https://pubg.sh/M0nk3yK0nG/xbox/241a7ec1-bf55-433a-bbfe-e53ac7c2a142

iirc pubg doesn't save the telemetry forever, so I've saved it here:

https://gist.github.com/dalanmiller/30083373d916d6914b3f941a20edf935

**Comment by apazzolini** [comment]
Should be fixed, unhandled case of a bot killing another bot.
