### ISSUE TITLE
Add support for the new map Taego

### ISSUE THREAD

**Issue by Otsomies** [pubgsh/client#77]
Right now the new map Taego is shown with the name Tiger_Main and when trying to look at the replays it doesn't show the actual replay and gives a bunch of errors.

Support for the new maps should be added similar way as was done with Paramo and other new maps.

See similar commits for Paramo for reference: 
https://github.com/pubgsh/client/commit/76656684a85a9a14a14f91626dd7d1e64e5e103e
https://github.com/pubgsh/client/commit/f3632eb5508403c0a78f266076f253af455580d7

___

![image](https://user-images.githubusercontent.com/15611777/124915240-fd08df80-dff9-11eb-9e4a-1ee00907872a.png)

**Comment by Otsomies** [comment]
Do i need contributor privileges in order to create branches and PR's?

**Comment by Otsomies** [comment]
@apazzolini ?

**Comment by lovethebomb** [comment]
@apazzolini I've created PR #78 which provides support for the new map and weapons.
