### ISSUE TITLE
"An error occurred :(" while fetching matches

### ISSUE THREAD

**Issue by Fergo** [pubgsh/client#83]
I'm not sure if it's related to the expired certificate on the website or not, but even if you agree to continue and search for a player name, it returns the message ```An error occurred :(```

**Comment by 132ndhitch** [comment]
I have the same problem by username foxdevilwild_ in steam plattform: https://pubg.sh/foxdevilwild_/steam

**Comment by apazzolini** [comment]
I don't play PUBG anymore. It's very unlikely I'll find the time to look into this. I would be more than happy to accept a patch though, it's likely a small tweak in the telemetry parsing.

**Comment by Otsomies** [comment]
The app doesn't give any errors in the console. 
It might be that one telemetry will break the whole system for the certain account. Maybe broken telemetry file from pubg or something like that?

**Comment by apazzolini** [comment]
I wiped the server's cache and @132ndhitch's user seems to be working now. ¯\_(ツ)_/¯

**Comment by Fergo** [comment]
Thank you very much! Glad you also updated it to support Deston!

**Comment by apazzolini** [comment]
That was all @Otsomies :)
